### ISSUE TITLE
Creation of the README.md file

### ISSUE THREAD

**Issue by brett-buskirk** [brett-buskirk/nyc-guide#3]
Create a README.md file as specified by the project requirements.

- [x] Brendan to create the README
- [x] Brett  will review
- [x] Brendan & Brett to reconcile edits
- [x] Merge README to main

**Comment by brett-buskirk** [comment]
@theprisoncoder, I created this ticket to track the workflow for the README file. Let me know if you have any questions.

**Comment by bngwanforbi** [comment]
Added a README.md, created a pull request.

**Comment by brett-buskirk** [comment]
It looks like the README is in good order, though it's still missing a few  pieces from the criteria. I know you're having issues with your GitHub accounts, so I'll edit the document appropriately. We still need to add:

- Contributor's section
- Instructions on how to set up the virtual environment
- How to install project dependencies with `pip`
- How to run the Django application

**Comment by bngwanforbi** [comment]
Thank you @brett-buskirk . Unfortunately I have been unable to resolve the issues with my GitHub account and my local machine as of yet. Will continue to troubleshoot.

**Comment by brett-buskirk** [comment]
No worries. I finished the work on the README and pushed it up. Looks like the project is ready to submit. Great work, @bngwanforbi!
